site_name: MpcForces-Extractor
site_url: https://manuel1618.github.io/mpcforces-extractor/

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Quick-Start: quick_start.md
  - App: app.md
  - Direct: source_code.md
  - Dev-Coverage: coverage.md

plugins:
  - search
  - mkdocstrings
  - coverage

extra:
  version:
    provider: mike
    default: latest
